### ISSUE TITLE
在你的readme文件中写清楚，需要自己写除了index的其他页面，免得浪费像我一样读者的时间。

### ISSUE THREAD

**Issue by gym02** [ArthurYung/react-my-website#59]

**Comment by ArthurYung** [comment]
你是想代码都不看就直接部署吗= =。
所有页面和代码都在，报错内容你稍微看下也能发现缺少图片。
我不知道你是从哪个渠道看到我的github，这个仓库放在github的目的是为了交流和学习参考，所以我图片资源是不公开的（这句话已在readme注释），因为我不希望出现一模一样的个人网站，这是有违我当时UI设计初衷的。
如果你喜欢这个风格，想部署一套一样的话，请你参考自己替换一套图片，希望能谅解。
